### ISSUE TITLE
Ingress configuration is outdated

### ISSUE THREAD

**Issue by tszebeni** [AzBuilder/terrakube-helm-chart#114]
Dear repo maintainers,
 I struggle to deploy terrakube, as ingress configuration is underdocumented/the provided example is no longer working.
The symptom:
"Error: INSTALLATION FAILED: 2 errors occurred:
        * admission webhook "validate.nginx.ingress.kubernetes.io" denied the request: nginx.ingress.kubernetes.io/configuration-snippet annotation cannot be used. Snippet directives are disabled by the Ingress administrator
        * admission webhook "validate.nginx.ingress.kubernetes.io" denied the request: nginx.ingress.kubernetes.io/configuration-snippet annotation cannot be used. Snippet directives are disabled by the Ingress administrator"
Actually the snippet annotations are disabled by default for nginx ingress controller.

Please update your documentation how to enable snippet annotations.

Thanks

**Comment by alfespa17** [comment]
Hello @tszebeni 

I added the comments to fix that issue in our documentation.

https://docs.terrakube.io/getting-started/deployment/minikube#install-terrakube

![image](https://github.com/AzBuilder/terrakube-helm-chart/assets/4461895/1d33f879-3c5c-48ba-93f4-eca86274d734)

In a high level you need to add "allow-snippet-annotations: "true"" in the  ingres-nginx-controller configMap in namespace ingress-nginx.

You can find the reference in this issue:

https://github.com/AzBuilder/terrakube/issues/618#issuecomment-1838980451
