### ISSUE TITLE
Workspaces not loading

### ISSUE THREAD

**Issue by MARVELMafia** [AzBuilder/terrakube-helm-chart#126]
I created an Organization and then a workspace inside that organization and I get the loading image.
![image](https://github.com/AzBuilder/terrakube-helm-chart/assets/28630442/e3896460-d960-4f44-9cb8-c302ccbd35b6)

When I go to the workspace page then I see 
![image](https://github.com/AzBuilder/terrakube-helm-chart/assets/28630442/f1287ea5-8560-4d15-84e8-b930cf36b920)

but when I click on the workspace I get the loading page again
![image](https://github.com/AzBuilder/terrakube-helm-chart/assets/28630442/e3896460-d960-4f44-9cb8-c302ccbd35b6)

The log on the api tell me a query is being queried but nothing after that
![image](https://github.com/AzBuilder/terrakube-helm-chart/assets/28630442/a42c687e-3bc2-48da-858d-dbe4689156dd)

**Comment by alfespa17** [comment]
I think you could check the browser logs maybe your token is expired or you can refresh the page
