### ISSUE TITLE
Customised path for Dex not working

### ISSUE THREAD

**Issue by stanleyz** [AzBuilder/terrakube-helm-chart#128]
There is a parameter in values.yaml to configure the path for Dex, namely `.Values.ingress.dex.path`, but `/dex` is refered in some places directly, for example in the below line

https://github.com/AzBuilder/terrakube-helm-chart/blob/57db6ad68d09073a340fcbf8ec319ea86c3e81b1/charts/terrakube/templates/secrets-registry.yaml#L17

**Comment by alfespa17** [comment]
Hello @stanleyz, you are right I think that part can be changed and take the value from the dex config path
