### ISSUE TITLE
Add init container/ability to install additional tools into executor container

### ISSUE THREAD

**Issue by ValeriiVozniuk** [AzBuilder/terrakube-helm-chart#134]
Some other helm charts are allowing to install additional tools via init containers (example: https://github.com/bitnami/charts/blob/main/bitnami/keycloak/templates/statefulset.yaml#L93).
It would be nice to see the same in terrakube helm chart to be able to install tools in the executor container.
In our case for our code we need envsubst and kubectl, and currently I'm doing it via Template run after container start, but it is not really a good way to do it.

**Comment by alfespa17** [comment]
Hello @ValeriiVozniuk you could create a custom image and you can add all the tools that you need inside the executor component similar to what we do to add git to the image.

You can check the pipiline:

https://github.com/AzBuilder/terrakube/blob/90321eb2c3fe9ca2eb33977a3b86ebf169f4cd5d/.github/workflows/release.yml#L66

**Comment by alfespa17** [comment]
You can also check this example to build terrakube and add other tools.

https://github.com/AzBuilder/terrakube/blob/90321eb2c3fe9ca2eb33977a3b86ebf169f4cd5d/scripts/build/terrakubeBuild.sh

**Comment by alfespa17** [comment]
By the way if anyone would like to help adding the initContainer feature like in the Bitnami helm chart from the above [example](https://github.com/bitnami/charts/blob/main/bitnami/keycloak/templates/statefulset.yaml#L93) all pull request are welcome

**Comment by ValeriiVozniuk** [comment]
> Hello @ValeriiVozniuk you could create a custom image and you can add all the tools that you need inside the executor component similar to what we do to add git to the executor image.

I see, thank you. For simple tools it has too much overhead, I'll stick with Template run for now then, and wait if someone would add an init container pull request :)
