### ISSUE TITLE
Executor Pod Seems to Require Elevated Permissions

### ISSUE THREAD

**Issue by fishfacemcgee** [AzBuilder/terrakube-helm-chart#153]
With just default settings, using the Helm chart leads to the Executor pod being in a failed state with `CreateContainerError` as the Pod's status and the Pod's events being

```
  Normal   Scheduled  27s                default-scheduler  Successfully assigned terrakube/terrakube-executor-podid to nodehostname
  Warning  Failed     26s                kubelet            Error: failed to create containerd container: mount callback failed on /var/lib/containerd/tmpmounts/containerd-mount2121130882: no users found
  Warning  Failed     26s                kubelet            Error: failed to create containerd container: mount callback failed on /var/lib/containerd/tmpmounts/containerd-mount2833052859: no users found
  Normal   Pulled     13s (x3 over 26s)  kubelet            Container image "azbuilder/executor:2.23.2" already present on machine
  Warning  Failed     13s                kubelet            Error: failed to create containerd container: mount callback failed on /var/lib/containerd/tmpmounts/containerd-mount2199440453: no users found
```

While trying to find an answer I came across an unrelated issue where someone provided their values and it modified permissions specifically for the Executor. After some tinkering with those values, this is now what I need in my values file in order for the pod to create successfully.

```yaml
executor:
  enabled: true
  securityContext:
    runAsUser: 0
```

All other pods created without issue, most of which were on the same node, so it seems unlikely to be an issue with the underlying node. For additional context:

* This is an EKS-based cluster running K8S 1.30
* The nodes in the cluster are ARM-based, running Bottlerocket OS
  * I would hope this wouldn't matter, but I also ran into ARM-related issues around Postgres (I think the bitnami package being used predates them having arm images) and the spring boot library, so I figured it's worth mentioning
    * https://github.com/AzBuilder/terraform-spring-boot/issues/52
    * https://github.com/AzBuilder/terrakube/issues/1477

**Comment by alfespa17** [comment]
Hello @fishfacemcgee 

For the issue related to downloading terraform you can try this executor version [2.23.3-beta.1](https://github.com/AzBuilder/terrakube/releases/tag/2.23.3-beta.1), it includes the fix that you sent earlier this morning.

**Comment by alfespa17** [comment]
For this one `ARM-related issues around Postgres` maybe you can try using an external database the one that is included in the helm chart is good for testing purposes, you could check [here](https://docs.terrakube.io/getting-started/deployment/database-backend/postgresql)

For the executor container creation issue, I am not really sure the 3 components (api, registry and executor) are created using the same buildpack the only difference is that we install some other dependencies like git as you can see [here](https://github.com/AzBuilder/terrakube/blob/7c5a087e89e8de91336c7bf8e67b3b382e3263bd/.github/workflows/release.yml#L75) 

by default the container are using user "cnb" with the following information

```shell
cnb@terrakube-executor-848f989f66-w6hc7:/workspace$ whoami
cnb
cnb@terrakube-executor-848f989f66-w6hc7:/workspace$ id
uid=1002(cnb) gid=1000(cnb) groups=1000(cnb)
```

Maybe using this (could work but I am not sure)

```yaml
executor:
  enabled: true
  securityContext:
    runAsUser: 1002
```

**Comment by fishfacemcgee** [comment]
@alfespa17 Happy to report that 2.23-beta.1 resolves the terraform install issue on ARM.

**Comment by fishfacemcgee** [comment]
And yeah, terrakube works fine with an external DB. I wasn't expecting to need to spin one up in the testing phase I'm in currently, but it was more of a "Oh, that's odd" than a hard deal breaker. As best I can tell, newer versions of bitnami's postgres are multi-arch, so a version bump there (not necessarily trivial, of course) might work as a more permanent "fix" for that. I'll give user 1002 a shot to see if that plays nice or not.

**Comment by fishfacemcgee** [comment]
@alfespa17 Using user 1002 solves the CreateContainerError but introduces a new error when trying to run terraform

```
[threadPoolTaskExecutor-1] INFO org.terrakube.terraform.TerraformDownloader - Initialize TerraformDownloader using custom URL
[threadPoolTaskExecutor-1] INFO org.terrakube.terraform.TerraformDownloader - User Home Directory: ?
[threadPoolTaskExecutor-1] ERROR org.terrakube.terraform.TerraformDownloader - Cannot create directory '?/.terraform-spring-boot/download'.
[threadPoolTaskExecutor-1] INFO org.terrakube.terraform.TerraformDownloader - Downloading terraform version 1.6.4 architecture aarch64 Type Linux
[threadPoolTaskExecutor-1] ERROR org.springframework.aop.interceptor.SimpleAsyncUncaughtExceptionHandler - Unexpected exception occurred invoking async method: public void org.terrakube.executor.service.executor.ExecutorJobImpl.createJob(org.terrakube.executor.service.mode.TerraformJob)
java.lang.NullPointerException: Cannot invoke "org.terrakube.terraform.TerraformResponse.getVersions()" because "this.terraformReleases" is null
	at org.terrakube.terraform.TerraformDownloader.downloadTerraformVersion(TerraformDownloader.java:222)
	at org.terrakube.terraform.TerraformClient.getTerraformLauncher(TerraformClient.java:284)
	at org.terrakube.terraform.TerraformClient.run(TerraformClient.java:209)
	at org.terrakube.terraform.TerraformClient.init(TerraformClient.java:105)
	at org.terrakube.executor.service.terraform.TerraformExecutorServiceImpl.executeTerraformInit(TerraformExecutorServiceImpl.java:404)
	at org.terrakube.executor.service.terraform.TerraformExecutorServiceImpl.plan(TerraformExecutorServiceImpl.java:107)
	at org.terrakube.executor.service.executor.ExecutorJobImpl.createJob(ExecutorJobImpl.java:53)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:355)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:113)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

It looks like the `cnb` user isn't making it to the created pod but instead a Heroku user is?

```
k -n terrakube exec -it terrakube-executor-5f96746fc-9svxg -- bash
I have no name!@terrakube-executor-5f96746fc-9svxg:/workspace$ whoami
whoami: cannot find name for user ID 1002
I have no name!@terrakube-executor-5f96746fc-9svxg:/workspace$ cat /etc/passwd
root:x:0:0:root:/root:/bin/bash
daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin
bin:x:2:2:bin:/bin:/usr/sbin/nologin
sys:x:3:3:sys:/dev:/usr/sbin/nologin
sync:x:4:65534:sync:/bin:/bin/sync
games:x:5:60:games:/usr/games:/usr/sbin/nologin
man:x:6:12:man:/var/cache/man:/usr/sbin/nologin
lp:x:7:7:lp:/var/spool/lpd:/usr/sbin/nologin
mail:x:8:8:mail:/var/mail:/usr/sbin/nologin
news:x:9:9:news:/var/spool/news:/usr/sbin/nologin
uucp:x:10:10:uucp:/var/spool/uucp:/usr/sbin/nologin
proxy:x:13:13:proxy:/bin:/usr/sbin/nologin
www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin
backup:x:34:34:backup:/var/backups:/usr/sbin/nologin
list:x:38:38:Mailing List Manager:/var/list:/usr/sbin/nologin
irc:x:39:39:ircd:/run/ircd:/usr/sbin/nologin
_apt:x:42:65534::/nonexistent:/usr/sbin/nologin
nobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin
sshd:x:100:65534::/run/sshd:/usr/sbin/nologin
heroku:x:1000:1000::/home/heroku:/bin/bash
```

LIkely something [in Heroku's buildpack](https://github.com/AzBuilder/terrakube/blob/7c5a087e89e8de91336c7bf8e67b3b382e3263bd/.github/workflows/release.yml#L59).

**Comment by alfespa17** [comment]
That is true the ARM image is using a different buildpack I forgot about that.

**Comment by fishfacemcgee** [comment]
At the very least, as a workaround, using 1000 as the `runAsUser` argument is doing what we hoped 1002 would do. Avoids the CreateContainerError and still lets terraform run.

**Comment by alfespa17** [comment]
> At the very least, as a workaround, using 1000 as the `runAsUser` argument is doing what we hoped 1002 would do. Avoids the CreateContainerError and still lets terraform run without having to run as root.

Do you still have the issue for `this.terraformReleases` ??

**Comment by fishfacemcgee** [comment]
Using 1000 as the user solves that error since the heroku user exists (so it's able to download the releases to a folder in its home directory).

As far as the root cause of the CreateContainerError, am I right in understanding that [these direct references to the cnb user](https://github.com/AzBuilder/terrakube/blame/7c5a087e89e8de91336c7bf8e67b3b382e3263bd/.github/workflows/release.yml#L76) would cause the issue as that user doesn't exist on the Heroku-buildpack'd executor?

**Comment by alfespa17** [comment]
> Using 1000 as the user solves that error since the heroku user exists (so it's able to download the releases to a folder in its home directory).
> 
> As far as the root cause of the CreateContainerError, am I right in understanding that [these direct references to the cnb user](https://github.com/AzBuilder/terrakube/blame/7c5a087e89e8de91336c7bf8e67b3b382e3263bd/.github/workflows/release.yml#L76) would cause the issue as that user doesn't exist on the Heroku-buildpack'd executor?

That is true, that will require some small fix in the pipeline when releasing the ARM version

**Comment by fishfacemcgee** [comment]
@alfespa17 I can confirm no more CreateContainerErrors when no `runAsUser` is defined and the spring boot fix is still working too. Thank you so much for all of your help.
