### ISSUE TITLE
gh-pages helm repo

### ISSUE THREAD

**Issue by Diliz** [AzBuilder/terrakube-helm-chart#43]
Hello there!

Can you add gh-pages to your repo so we can use it as a helm repository? :)

As an example on how to set it up:
https://helm.sh/docs/howto/chart_releaser_action/

An example repository where it's already done:
https://github.com/prometheus-community/helm-charts

Thanks for your hard work ;)

**Comment by alfespa17** [comment]
It doesn`t look so difficult, I will check this

**Comment by alfespa17** [comment]
I added the helm repository configuration.

https://azbuilder.github.io/terrakube-helm-chart/

```bash
helm repo add terrakube-community https://AzBuilder.github.io/terrakube-helm-chart
"terrakube-community" has been added to your repositories
```

Thank you for the suggestion @Diliz

**Comment by Diliz** [comment]
Nice! Thanks!
