### ISSUE TITLE
helm chart fundamentally incompatible with secure gitops

### ISSUE THREAD

**Issue by jstewart612** [AzBuilder/terrakube-helm-chart#59]
Because you force passing in of sensitive credentials in Helm chart values, this Helm chart cannot safely be used with many GitOps tools, such as ArgoCD.

Add support for specifying all sensitive values using an existing secret.  This way, the user can facilitate its placement using secure means (like Hashicorp Vault for example, or many others).

**Comment by jstewart612** [comment]
I have put up a proposed alternative that would, on a basic level, allow you to bring your own secrets for properly secure Gitops.  It would add a simple existingSecret toggle to the relevant secrets which, if set false, the Helm chart wouldn't render the aforementioned secrets.

**Comment by alfespa17** [comment]
Hello @jstewart612 I undertstand that your PR fixed the issue on a basic level because now you can provide your secrets before installling the helm chart, what could be the best practice or more advance way to handle the secret for those scenarios? do you have any recommendation?
