### ISSUE TITLE
Deployment example if use single domain for all components (UI/API/Dex/Registry) ingresses + storage backend authentication using roles + jdbc connection url with ssl

### ISSUE THREAD

**Issue by kspradheep** [AzBuilder/terrakube-helm-chart#74]
1) Trying to setup all components (UI/API/Dex/Registry) ingresses using same domain (terrakube.mycompany.com) and prefix-based routing.
UI ingress path: terrakube.mycompany.com/ui
API ingress path: terrakube.mycompany.com/api
Dex ingress path: terrakube.mycompany.com/dex
Registry ingress path: terrakube.mycompany.com/reg

However, the ingresses are not working. Does terrakube support prefix-based routing? 

2) Created postgressql cluster using Zalando postgres operator (https://github.com/zalando/postgres-operator/blob/master/manifests/complete-postgres-manifest.yaml) Terrakube postgressql connection fails with no encryption if connected to external postgres database
Caused by: liquibase.exception.DatabaseException: org.postgresql.util.PSQLException: FATAL: pg_hba.conf rejects connection for host "10.xxx.xxx.xx", user "terrakube", database "terrakube", no encryption
How to pass or override jdbc connection url?

3) Is it possible to configure IAM role instead of access key and secret key for AWS S3 storage if runs in EKS kubernetes cluster?

**Comment by alfespa17** [comment]
I will close this issue as is duplicated https://github.com/AzBuilder/terrakube/issues/452
