### ISSUE TITLE
Helm Chart External Redis Value

### ISSUE THREAD

**Issue by ilkerispir** [AzBuilder/terrakube-helm-chart#86]
Hello @alfespa17, @jcanizalez,

I want to use my own redis cluster in the Terrakube Helm chart instead of the Bitnami Redis Chart by default. Just like storage and database services. Is there a chance to update the current Helm Chart for this?

![image](https://github.com/AzBuilder/terrakube-helm-chart/assets/37123041/cf911a31-8572-46ce-90f7-a02a43cb022f)

**Comment by alfespa17** [comment]
Hello @ilkerispir 

I think we can add some parameters to handle that it should not be a huge change, I could try to add it in the following days

Regards.

**Comment by alfespa17** [comment]
By the way if you would like to help with the change feel free to send a pull request, all help is welcome.

**Comment by ilkerispir** [comment]
@alfespa17, thank you for your message. Yes, I would definitely like to help you. I'll create a PR for this issue in the coming days.

**Comment by ilkerispir** [comment]
Hello again @alfespa17,

I created the PR for the addition of the external Redis option, which is the subject we are talking about here. I couldn't add you and @jcanizalez as a review because I don't have permission.

Could you please review my PR when you're available? PR: https://github.com/AzBuilder/terrakube-helm-chart/pull/87

**Comment by alfespa17** [comment]
Thank you @ilkerispir I will check the PR and let you know if I have any comments

**Comment by alfespa17** [comment]
Now you can use the helm chart 3.10.1 when you need to use an external redis. Thank you @ilkerispir
